name: fallAppEnv
channels:
  - defaults
  - conda-forge
dependencies:
  - asgiref=3.8.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - django=5.1.3
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=25.0
  - python=3.11.11
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - sqlparse=0.5.2
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - djangorestframework==3.15.2
      - idna==3.10
      - requests==2.32.3
      - urllib3==2.3.0
