#!/bin/bash

SESSION_NAME="sensor_pipeline"

# 1. Start a new tmux session on your Mac
tmux new-session -d -s $SESSION_NAME

# 2. In Pane 0: SSH into Pi and run the sensor script
tmux send-keys -t $SESSION_NAME:0 'ssh jacobopatz@578pi "eval \"\$(/opt/miniconda/bin/conda shell.bash hook)\" && conda activate fallAppEnv && python \"/home/jacobopatz/CS578-Project/client program/detectFall.py\""
' C-m

# 3. Split the tmux window horizontally for Django server (Pane 1)
tmux split-window -v -t $SESSION_NAME

# 4. In Pane 1: Run the Django server locally and start Tailscale Funnel
tmux send-keys -t $SESSION_NAME:0.1 'cd falldetectionapp && conda activate fallAppEnv && python manage.py runserver 0.0.0.0:8000 & tailscale funnel 8000' C-m

# 5. Attach to the tmux session so you can view both processes
tmux attach -t $SESSION_NAME
