# Generated by Django 5.1.3 on 2025-03-03 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashBoard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
